### PR TITLE
move call to onSlideChange into goToSlide.  Jacse/react-native-app-intro-slider#111

### PR DESCRIPTION
**Pull request by yaronsha**
…

### CODE REVIEW

**Comment by Jacse** [comment]
If we do this then behaviour changes a little. Now, when the `goToSlide`-function is called programatically (e.g. not the end-user changing slides), `onSlideChange` is fired even though the user did not change slides. I'm not sure if that would be expected behaviour.

**Comment by Hirbod** [comment]
Well, imho onSlideChange should ALWAYS be called, when the slide changes, no matter if it was done by the user or programatically. When I press the pagination dots, onSlideChange won't get fired, which is bad :/

**Comment by Hirbod** [comment]
What I basically wanted to say: can you release a new version containing this fix please? I pinned this Github Dev for now

**Comment by georgiosd** [comment]
@Hirbod @Jacse is this working for you guys? It doesnt seem to get called on 4.0.2

**Comment by Hirbod** [comment]
No @georgiosd I switched to this fork long time ago:
https://github.com/Richi2293/rn-falcon-app-intro

It's maintained and received all the important bug fixes. But I discovered this one here few days ago which looks also pretty neat:
https://github.com/gorhom/react-native-paper-onboarding

**Comment by georgiosd** [comment]
For anyone looking at this, you need to `goToSlide(idx, true)` for the event to be called

**Pull request merged**
