### PR TITLE
Add index props to renderItem

### PR DESCRIPTION
**Pull request by nicomontanari98**
I added the item index to renderItem method props

### CODE REVIEW

**Comment by nicomontanari98** [comment]
@Jacse Can you merge this pull request?

**Comment by Jacse** [comment]
I think it is a good idea to move towards a more `FlatList`-style `renderItem`-function. Could you update the README as well?

**Comment by nicomontanari98** [comment]
Ok @Jacse, i did it

**Comment by Jacse** [comment]
Actually, I think we should replicate the `renderItem`-fuction arguments from `FlatList` like so: `renderItem({ item, index, dimensions})` where dimensions is an object containing width and height. This would require a new major version, but I think it makes sense. What do you think?

**Comment by nicomontanari98** [comment]
It is a good idea but i think that we could just do this into _renderItem function:
`const props = { ...item, dimensions: { width, height } }`

**Comment by Jacse** [comment]
@nicomontanari98 Yeah, let's do that for a minor version and then change it for a major release :)

I'm super busy atm, but I'll merge this asap

**Comment by nicomontanari98** [comment]
At the moment i changed the code, but we have to update the documentation

**Comment by nicomontanari98** [comment]
Hi @Jacse, i made everything

**Pull request merged**
