### PR TITLE
Change slide key from number to string

### PR DESCRIPTION
**Pull request by jorjordandan**
Prevents warning -> "Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`. "  from Flatlist data attribute.
Avoids the warning for people copying code from the readme :)

### CODE REVIEW

**Comment by jorjordandan** [comment]
Further discussion here: https://github.com/facebook/react-native/issues/18291

**Comment by Jacse** [comment]
Could you update the examples as well?

**Comment by jorjordandan** [comment]
None of the examples use a number as a key prop - they use the key extractor function to get the item title, so they should be fine.

**Comment by Jacse** [comment]
Ah of course.

**Pull request merged**
