### PR TITLE
Added a renderDots function

### PR DESCRIPTION
**Pull request by compojoom**
It can be used to supply a new dots component.

In our case we had a little more "complicated" design where we need to render a border on the active dot item. You could solve this by specifying new style object for the dot, but I think that having the option to render the dots yourself is better.

### CODE REVIEW

**Comment by Jacse** [comment]
Thanks for the PR and good job.

As a matter of principle, I don't like adding props that only solve edge-cases because I think that pollutes the options of the component. I agree that customisation is important, but I don't see the demand for a custom `renderDots` function, considering that the style-props should cover by far the most use cases, including your own.

I'll close for now, but please let me know if you disagree. If we see more demand for this functionality in the future we'll reopen.

**Comment by compojoom** [comment]
@Jacse - well. Ok. if you don't allow overriding the function, than I think that you should allow proviging a custom activeDotStyle and a custom inactiveDotStyle - not just a color prop

Also if you don't provide the option to overide the _renderDots, then at least a hideDots setting would be helpful.  

What do you think?

**Comment by Jacse** [comment]
@compojoom I thought that was already the case, you're completely right! Actually I think we should remove the `activeDotColor` and introduce an `activeDotStyle`-prop instead. Same goes for `dotColor` -> `inactiveDotStyle`. Do you want to submit a new PR for that?

**Comment by compojoom** [comment]
Ok, I'll make a new PR

**Pull request closed without merging**
