### PR TITLE
Fixes bottom Spacing when status bar is translucent in android

### PR DESCRIPTION
**Pull request by HarishJangra**
style set to flex:1 instead of height in item

### CODE REVIEW

**Comment by TomasAmaro** [comment]
I was about to do something to fix this.
Instead of using `const { width, height } = Dimensions.get('window');`
Use `const { width, height } = Dimensions.get('screen');`

But anyway, Your solution looks much nicer. Tested and it's ok in a bunch of phones!

**Comment by Jacse** [comment]
Does this also work if you switch between landscape and portrait?

**Comment by HarishJangra** [comment]
> Does this also work if you switch between landscape and portrait?

I have not tested that actually as it was not in my use case.

**Comment by Jacse** [comment]
Awesome work

**Pull request merged**
