### PR TITLE
disable gesture swipe

### PR DESCRIPTION
**Pull request by valdio**

### CODE REVIEW

**Comment by Jacse** [comment]
Could you briefly explain what functionality this adds compared to `scrollEnabled`?

**Comment by valdio** [comment]
@Jacse I had a use case when I needed to disable the "Go to next slide" action with swipe gestures. 

The code I pushed in this pull request does just that. It disables the swipe gestures and you can go to the next slides only on NEXT button press.

**Comment by Jacse** [comment]
Doesn't that work by setting `scrollEnabled={false}`?

**Comment by valdio** [comment]
If you just do `scrollEnabled={false}` it disables scrolling all together and the swiping does not work at all.

**Comment by Jacse** [comment]
You should still be able to click next/prev buttons, I believe, if that's what you mean.

**Comment by valdio** [comment]
Yes.

**Comment by Jacse** [comment]
I'm not sure what extra functionality this adds then @valdio ?

**Comment by Jacse** [comment]
I'm going to close this for now, but please feel free to elaborate.

**Pull request closed without merging**
