### PR TITLE
Render button

### PR DESCRIPTION
**Pull request by compojoom**
I wanted to show a full page button when the user is on the last screen. Unfortunatly the button button has styling . To overcome this I added a renderButton function. This way if one needs special buttons, one can now implement them

### CODE REVIEW

**Comment by Jacse** [comment]
What's the added use case compared to `renderNextButton`, `renderDoneButton`.... etc. ?

**Comment by compojoom** [comment]
@Jacse - the last scene in my case shouldn't show the done button on the right together with the dots. All I want to show there is a big "start now" button.

I was able to hack my way by listening onSlideChange and setting showBottomButton to true when on last slide. But you have a style for that button (transparent background etc) and I needed to have a different style. By having a renderButton I was able to serve the styles I need for my bottomButton.

**Comment by Jacse** [comment]
@compojoom I see what you mean. While it might feel a slight bit "hacky" I don't think changing `bottomButton` in a `onSlideChange` is a bad way to go about it. I honestly don't like "exposing" the `renderButton`-function as it was always meant as an internal convenience-function. Couldn't you use `renderDoneButton` in your case? That would allow you custom styling of the button.

**Comment by compojoom** [comment]
No, no. The hacky thing was fine. The problem was the bottomButton. the view containing the button has a semi-transparent black background. I didn't need this. My button has border and is transparent. If you don't want to expose this what might work is adding a style properties to the bottomContainer and to the bottomButton. This way I could provide custom styling. I also don't like the _renderButton function as it's actually the same as yours, but my styles are different.

I'll see if providing property styles could fix this.

**Comment by Jacse** [comment]
Ah I see now. I think the problem lies in the fact that the containing view is forced on the buttons even when a custom `renderXButton` has been defined. In effect, that renders it impossible to fully control the styles even with a custom function, which is obviously not ideal.

In think the correct solution is to move the containing view into the render functions of each button instead. I'll throw something together in a minute.

**Pull request closed without merging**
